config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  root 'welcome#index'
  resources :location_types
  resources :location_contacts
  resources :locations 
  resources :location_ip_schemas
  get '/search_location_for_ip', to: 'location_ip_schemas#search', as: 'search_location_for_ip'
  get '/find_location', to: 'location_ip_schemas#find_location', as: 'find_location'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ip.rb
class Ip
  include ActiveModel::Validations
  attr_reader :ip 

  def initialize(ip=nil)
    @ip = ip
  end

  validates :ip, presence: true, 
  format: { with: /\A(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\z/i, message: "please enter a valid ip address"}
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :location_type 
  has_many :location_ip_schema, dependent: :destroy
  has_many :location_contact, dependent: :destroy
  validates :location_name, presence: true, uniqueness: {case_sensitive: false}, 
                            length: {minimum: 2, maximum: 25}
end

app/models/location_contact.rb
class LocationContact < ApplicationRecord
  belongs_to :location 
  validates :name, presence: true,  uniqueness: {case_sensitive: false}, 
  length: {minimum: 2, maximum: 25} 
  validates :number, presence: true, length: {minimum: 6, maximum: 30}
  validates :email, presence: true
end

app/models/location_ip_schema.rb
class LocationIpSchema < ApplicationRecord
  belongs_to :location 
  validates :network, presence: true, 
  format: { with: /\A(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\z/i, message: "please enter network in correct format e.g 172.16.10.0"}
  validates :subnet, presence: true, 
  format: { with: /\A(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\z/i, message: "please enter subnet in correct format e.g 255.255.255.0"}

  def self.search_location(given_ip) 
    self.all.each do |ip_schema| 
      the_network = IPAddr.new("#{ip_schema.network}/#{ip_schema.subnet}")
      begin
      if the_network.include? "#{given_ip}" 
        return ip_schema.location
      end
      rescue IPAddr::InvalidAddressError
        return false
      end
    end
    return false
  end

end

app/models/location_type.rb
class LocationType < ApplicationRecord
  has_many :location, dependent: :destroy
  validates :location_type, presence: true,  uniqueness: {case_sensitive: false}, 
                             length: {minimum: 2, maximum: 25} 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/location_contacts_controller.rb
class LocationContactsController < ApplicationController 
  before_action :set_location_contact, only: [:show, :update, :destroy, :edit]

  def new 
    @location_contact = LocationContact.new 
  end

  def create 
    @location_contact = LocationContact.new(set_location_contact_params) 
    if @location_contact.save
      flash[:notice] = "Location Contact is successfully created" 
      redirect_to location_contacts_path
    else
      render 'new'
    end
  end
  
  def edit 
  end 

  def show 
  end

  def update 
    if @location_contact.update(set_location_contact_params)
      flash[:notice] = "Location Contact was successfully updated"
      redirect_to @location_contact  
    else
      render 'edit'
    end
  end

  def destroy 
    @location_contact.destroy 
    flash[:notice] = "Location Contact was successfully deleted"
    redirect_to location_contacts_path  
  end

  def index 
    @location_contacts = LocationContact.all 
  end

  private 
  def set_location_contact_params 
    params.require(:location_contact).permit(:name, :number, :email, :location_id, :comment)
  end

  def set_location_contact 
    @location_contact = LocationContact.find(params[:id])
  end
end

app/controllers/location_ip_schemas_controller.rb
class LocationIpSchemasController < ApplicationController 
  before_action :set_location_ip_schema, only: [:show, :update, :destroy, :edit]

  def new 
    @location_ip_schema = LocationIpSchema.new 
  end

  def create 
    @location_ip_schema = LocationIpSchema.new(set_location_ip_schema_params) 
    if @location_ip_schema.save
      flash[:notice] = "Location IP Schema is successfully created" 
      redirect_to location_ip_schemas_path
    else
      render 'new'
    end
  end
  
  def edit 
  end 

  def show 
  end

  def update 
    if @location_ip_schema.update(set_location_ip_schema_params)
      flash[:notice] = "Location IP Schema was successfully updated"
      redirect_to @location_ip_schema  
    else
      render 'edit'
    end
  end

  def destroy 
    @location_ip_schema.destroy 
    flash[:notice] = "Location IP Schema was successfully deleted"
    redirect_to location_ip_schemas_path  
  end

  def index 
    @location_ip_schemas = LocationIpSchema.all 
  end
  
  def search 
  end

  def find_location 
    ip = Ip.new(params["anything"][:ip])
    if ip.valid?
      location = LocationIpSchema.search_location(ip.ip) 
      if location 
        @location = location 
        respond_to do |format| 
          format.js { render partial: 'location_ip_schemas/location'}
        end
      else 
        respond_to do |format| 
          flash.now[:alert] = "Location for IP #{ip.ip} could not be found" 
          format.js { render partial: 'location_ip_schemas/location'}
        end
      end
    else
      @ip = ip
      respond_to do |format| 
        format.js { render partial: 'location_ip_schemas/location'}
      end
    end
  end

  private 
  def set_location_ip_schema_params 
    params.require(:location_ip_schema).permit(:network, :subnet, :comment, :location_id)
  end

  def set_location_ip_schema 
    @location_ip_schema = LocationIpSchema.find(params[:id])
  end
end

app/controllers/location_types_controller.rb
class LocationTypesController < ApplicationController 
  before_action :set_location_type, only: [:show, :update, :destroy, :edit]

  def new 
    @location_type = LocationType.new 
  end

  def create 
    @location_type = LocationType.new(set_location_type_params) 
    if @location_type.save
      flash[:notice] = "Location Type is successfully created" 
      redirect_to location_types_path
    else
      render 'new'
    end
  end
  
  def edit 
  end 

  def show 
  end

  def update 
    if @location_type.update(set_location_type_params)
      flash[:notice] = "Location Type was successfully updated"
      redirect_to @location_type  
    else
      render 'edit'
    end
  end

  def destroy 
    @location_type.destroy 
    flash[:notice] = "location type was successfully deleted"
    redirect_to location_types_path  
  end

  def index 
    @location_types = LocationType.all 
  end

  private 
  def set_location_type_params 
    params.require(:location_type).permit(:location_type, :comment)
  end

  def set_location_type 
    @location_type = LocationType.find(params[:id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController 
  before_action :set_location, only: [:show, :update, :destroy, :edit]

  def new 
    @location = Location.new 
  end

  def create 
    @location = Location.new(set_location_params) 
    if @location.save
      flash[:notice] = "Location is successfully created" 
      redirect_to locations_path
    else
      render 'new'
    end
  end
  
  def edit 
  end 

  def show 
  end

  def update 
    if @location.update(set_location_params)
      flash[:notice] = "Location was successfully updated"
      redirect_to @location  
    else
      render 'edit'
    end
  end

  def destroy 
    @location.destroy 
    flash[:notice] = "location was successfully deleted"
    redirect_to locations_path  
  end

  def index 
    @locations = Location.all 
  end

  private 
  def set_location_params 
    params.require(:location).permit(:location_name, :location_type_id, :location_address, :comment)
  end

  def set_location 
    @location = Location.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index 
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">Location Manager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Location
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Index", locations_path, class: "dropdown-item" %>
            <%= link_to "Create", new_location_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Location Types
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Index", location_types_path, class: "dropdown-item" %>
            <%= link_to "Create", new_location_type_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Location Contacts
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Index", location_contacts_path, class: "dropdown-item" %>
            <%= link_to "Create", new_location_contact_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Location IP Schema
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Index", location_ip_schemas_path, class: "dropdown-item" %>
            <%= link_to "Create", new_location_ip_schema_path, class: "dropdown-item" %>
            <%= link_to "Location IP search", search_location_for_ip_path, class: "dropdown-item" %>
          </div>
        </li>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
        <% end %>
      </ul>
      <% if user_signed_in? %>
      <ul class="navbar-nav mr-right">
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, class: 'nav-link', method: :delete %>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocationManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/location_contacts/_form.html.erb
<div class="container custom-page">
  <div class="row justify-content-center">
    <div class="col-10">
        <%= render 'shared/form_error', obj:@location_contact %>
        <%= form_with(model: @location_contact, class: "shadow p-3 mb-3 rounded", local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :"Name", class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter Contact Name" %>
              </div>
          </div>
          <div class="form-group row">
            <%= f.label :"Number", class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :number, class: "form-control shadow rounded", placeholder: "Enter Contact Number" %>
              </div>
          </div>
          <div class="form-group row">
            <%= f.label :"Email", class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter Contact email" %>
              </div>
          </div>
          <div class="form-group row">
            <%= f.label :"Location", class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.collection_select( :location_id, Location.all, :id, :location_name, {}, 
                { class: "form-control shadow rounded" }) %>
              </div>
          </div>
          <div class="form-group row">
            <%= f.label :comment, class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :comment, class: "form-control shadow rounded", placeholder: "Enter a comment" %>
              </div>
          </div>
          <div class="form-group row justify-content-center">
            <%= f.submit(@location_contact.new_record? ? "Create" : "Update", class: "btn btn-outline-light btn-lg") %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/location_contacts/edit.html.erb
<h1 class="text-center text-white mt-4">Edit a location contact</h1>
<%= render 'form' %>

app/views/location_contacts/index.html.erb
<h1 class="text-center text-white mt-4">Location Contacts</h1>
<div class="container mt-4">
  <table class="table table-striped table-secondary index-page">
    <thead class="text-center text-white">
      <tr>
        <th scope="col">Contact Name</th>
        <th scope="col">Contact Number</th>
        <th scope="col">Contact Email</th>
        <th scope="col">Location</th>
        <th scope="col">Location Type</th>
        <th scope="col">Comment</th>
        <th colspan="3">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @location_contacts.each do |location_contact| %>
        <tr class="text-center">
          <td><%= location_contact.name %></td>
          <td><%= location_contact.number %></td>
          <td><%= location_contact.email %></td>
          <td><%= location_contact.location.location_name %></td>
          <td><%= location_contact.location.location_type.location_type %></td>
          <td><%= location_contact.comment %></td>
          <td><%= link_to "View", location_contact_path(id: location_contact.id), class: "btn btn-outline-success" %></td>
          <td><%= link_to "Edit", edit_location_contact_path(id: location_contact.id), class: "btn btn-outline-info" %></td>
          <td><%= link_to "Delete", location_contact_path(id: location_contact.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/location_contacts/new.html.erb
<h1 class="text-center text-white mt-4">Create a new location contact</h1>
<%= render 'form' %>

app/views/location_contacts/show.html.erb
<h1 class="text-center mt-4">Location Contact Details</h1>
<div class="container text-white text-center">
  <div class="jumbotron custom-page">
    <p>Contact Name: <%= @location_contact.name %></p> 
    <p>Contact Number: <%= @location_contact.number %></p> 
    <p>Contact Email: <%= @location_contact.email %></p> 
    <p>Location: <%= @location_contact.location.location_name %></p>
    <p>Location Type: <%= @location_contact.location.location_type.location_type %></p>
    <p>Comment: <%= @location_contact.comment %></p>
    <p>
      <%= link_to "Edit", edit_location_contact_path(id: @location_contact.id), class: "btn btn-outline-info" %> 
      <%= link_to "Delete", location_contact_path(id: @location_contact.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
    </p>
  </div>
</div>

app/views/location_ip_schemas/_form.html.erb
<div class="container custom-page">
  <div class="row justify-content-center">
    <div class="col-10">
        <%= render 'shared/form_error', obj:@location_ip_schema %>
        <%= form_with(model: @location_ip_schema, class: "shadow p-3 mb-3 rounded", local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :"Location Network", class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :network, class: "form-control shadow rounded", placeholder: "Enter location network" %>
              </div>
          </div>
          <div class="form-group row">
            <%= f.label :"Location Subnet", class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :subnet, class: "form-control shadow rounded", placeholder: "Enter location subnet" %>
              </div>
          </div>
          <div class="form-group row">
            <%= f.label :"Location", class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.collection_select( :location_id, Location.all, :id, :location_name, {}, 
                { class: "form-control shadow rounded" }) %>
              </div>
          </div>
          <div class="form-group row">
            <%= f.label :comment, class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :comment, class: "form-control shadow rounded", placeholder: "Enter a comment" %>
              </div>
          </div>
          <div class="form-group row justify-content-center">
            <%= f.submit(@location_ip_schema.new_record? ? "Create" : "Update", class: "btn btn-outline-light btn-lg") %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/location_ip_schemas/_location.html.erb
<% if @ip %>
  <div class="results-block">
    <%= render 'shared/form_error', obj:@ip %>
  </div>
<% end %>

<%= render 'shared/flash' %>

<% if @location %>
<div class="container custom-page">
  <div class="row justify-content-center">
    <div class="col-10">
      <h1>Location Name: <%= @location.location_name %> </h1>
      <h2>Location Type: <%= @location.location_type.location_type %> </h2>
    </div> 
  </div> 
</div>
<% end %>

app/views/location_ip_schemas/_location.js.erb
document.querySelector('#location').innerHTML = '<%= j render 'location_ip_schemas/location.html' %>'

app/views/location_ip_schemas/edit.html.erb
<h1 class="text-center text-white mt-4">Edit a location ip schema</h1>
<%= render 'form' %>

app/views/location_ip_schemas/index.html.erb
<h1 class="text-center text-white mt-4">Locations IP Schema</h1>
<div class="container mt-4">
  <table class="table table-striped table-secondary index-page">
    <thead class="text-center text-white">
      <tr>
        <th scope="col">Location Network</th>
        <th scope="col">Location Subnet</th>
        <th scope="col">Location</th>
        <th scope="col">Location Type</th>
        <th scope="col">Comment</th>
        <th colspan="3">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @location_ip_schemas.each do |location_ip_schema| %>
        <tr class="text-center">
          <td><%= location_ip_schema.network %></td>
          <td><%= location_ip_schema.subnet %></td>
          <td><%= location_ip_schema.location.location_name %></td>
          <td><%= location_ip_schema.location.location_type.location_type %></td>
          <td><%= location_ip_schema.comment %></td>
          <td><%= link_to "View", location_ip_schema_path(id: location_ip_schema.id), class: "btn btn-outline-success" %></td>
          <td><%= link_to "Edit", edit_location_ip_schema_path(id: location_ip_schema.id), class: "btn btn-outline-info" %></td>
          <td><%= link_to "Delete", location_ip_schema_path(id: location_ip_schema.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/location_ip_schemas/new.html.erb
<h1 class="text-center text-white mt-4">Create a new location ip schema</h1>
<%= render 'form' %>

app/views/location_ip_schemas/search.html.erb
<h1 class="text-center text-white mt-4">Find location of any IP</h1>
<div class="container custom-page">
  <div class="row justify-content-center">
    <div class="col-10">
      <div class="mt-4">
        <% if @ip %> 
          <%= render 'shared/form_error', obj:@ip %>
        <% end %>
      </div>
      <%= form_for :anything, url: find_location_path, remote:true, method: :get do |f| %>
        <div class="form-group row mt-4">
          <%= f.label :"Search For IP", class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :ip, class: "form-control shadow rounded", id: "ip_field",placeholder: "Enter an IP" %>
            </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit "Find Location", class: "btn btn-outline-danger btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div id="location">

</div>

app/views/location_ip_schemas/show.html.erb
<h1 class="text-center mt-4">Location IP Schema details</h1>
<div class="container text-white text-center">
  <div class="jumbotron custom-page">
    <p>Location : <%= @location_ip_schema.location.location_name %></p>
    <p>Location Type: <%= @location_ip_schema.location.location_type.location_type %></p> 
    <p>Location Network: <%= @location_ip_schema.network %></p> 
    <p>Location Subnet: <%= @location_ip_schema.subnet %></p> 
    <p>Comment: <%= @location_ip_schema.comment %></p>
    <p>
      <%= link_to "Edit", edit_location_ip_schema_path(id: @location_ip_schema.id), class: "btn btn-outline-info" %> 
      <%= link_to "Delete", location_ip_schema_path(id: @location_ip_schema.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
    </p>
  </div>
</div>

app/views/location_types/_form.html.erb
<div class="container custom-page">
  <div class="row justify-content-center">
    <div class="col-10">
        <%= render 'shared/form_error', obj:@location_type %>
        <%= form_with(model: @location_type, class: "shadow p-3 mb-3 rounded", local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :"Location Type", class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :location_type, class: "form-control shadow rounded", placeholder: "Enter location type (PLANT, DC, OFFICE etc)" %>
              </div>
          </div>
          <div class="form-group row">
            <%= f.label :comment, class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :comment, class: "form-control shadow rounded", placeholder: "Enter a comment" %>
              </div>
          </div>
          <div class="form-group row justify-content-center">
            <%= f.submit(@location_type.new_record? ? "Create" : "Update", class: "btn btn-outline-light btn-lg") %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/location_types/edit.html.erb
<h1 class="text-center text-white mt-4">Edit a location type</h1>
<%= render 'form' %>

app/views/location_types/index.html.erb
<h1 class="text-center text-white mt-4">Location Types</h1>
<div class="container mt-4">
  <table class="table table-striped table-secondary index-page">
    <thead class="text-center text-white">
      <tr>
        <th scope="col">Location Type</th>
        <th scope="col">Comment</th>
        <th colspan="3">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @location_types.each do |location_type| %>
        <tr class="text-center">
          <td><%= location_type.location_type %></td>
          <td><%= location_type.comment %></td>
          <td><%= link_to "View", location_type_path(id: location_type.id), class: "btn btn-outline-success" %></td>
          <td><%= link_to "Edit", edit_location_type_path(id: location_type.id), class: "btn btn-outline-info" %></td>
          <td><%= link_to "Delete", location_type_path(id: location_type.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/location_types/new.html.erb
<h1 class="text-center text-white mt-4">Create a new location type</h1>
<%= render 'form' %>

app/views/location_types/show.html.erb
<h1 class="text-center mt-4">Location Type Details</h1>
<div class="container text-white text-center">
  <div class="jumbotron custom-page">
    <p>Location Type: <%= @location_type.location_type %></p> 
    <p>Comment: <%= @location_type.comment %></p>
    <p>
      <%= link_to "Edit", edit_location_type_path(id: @location_type.id), class: "btn btn-outline-info" %> 
      <%= link_to "Delete", location_type_path(id: @location_type.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
    </p>
  </div>
</div>

app/views/locations/edit.html.erb
<h1 class="text-center text-white mt-4">Edit a location</h1>
<%= render 'form' %>

app/views/locations/index.html.erb
<h1 class="text-center text-white mt-4">Location</h1>
<div class="container mt-4">
  <table class="table table-striped table-secondary index-page">
    <thead class="text-center text-white">
      <tr>
        <th scope="col">Location Name</th>
        <th scope="col">Location Type</th>
        <th scope="col">Location Address</th>
        <th scope="col">Comment</th>
        <th colspan="3">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @locations.each do |location| %>
        <tr class="text-center">
          <td><%= location.location_name %></td>
          <td><%= location.location_type.location_type %></td>
          <td><%= location.location_address %></td>
          <td><%= location.comment %></td>
          <td><%= link_to "View", location_path(id: location.id), class: "btn btn-outline-success" %></td>
          <td><%= link_to "Edit", edit_location_path(id: location.id), class: "btn btn-outline-info" %></td>
          <td><%= link_to "Delete", location_path(id: location.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/locations/new.html.erb
<h1 class="text-center text-white mt-4">Create a new location</h1>
<%= render 'form' %>

app/views/locations/show.html.erb
<h1 class="text-center mt-4">Location Details</h1>
<div class="container text-white text-center">
  <div class="jumbotron custom-page">
    <p>Location Name: <%= @location.location_name %></p>
    <p>Location Type: <%= @location.location_type.location_type %></p> 
    <p>Location Address: <%= @location.location_address %></p>
    <p>Comment: <%= @location.comment %></p>
    <p>
      <%= link_to "Edit", edit_location_path(id: @location.id), class: "btn btn-outline-info" %> 
      <%= link_to "Delete", location_path(id: @location.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
    </p>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <% if name == "notice" %>
      <div class="alert success-box alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% else %> 
      <div class="alert alert-box alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_form_error.html.erb
<% if !obj.errors.full_messages.empty? %>
<div class="container">
  <% obj.errors.full_messages.each do |msg| %>
    <div class="alert alert-box alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>
<% end %>